### ISSUE TITLE
Integration with testing frameworks

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-Prototype#30]
We need: 

- [x] Integration with unit testing framework (on push; e.g., Travis CI) 

- [x] Integration with test coverage checking, e.g., coveralls (https://coveralls.io/)

- [x] A system for testing containers

**Comment by mortenwh** [comment]
Commenting here instead of the sub-tasks... I though we would prioritize CI? Can we add it to the backlog? @aheimsbakk @mpejcoch
